"""Added scoring fields with 2 and 3 PT to stat model

Revision ID: 7160dd251d6a
Revises: a789ec0b26df
Create Date: 2025-07-19 22:27:52.218037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7160dd251d6a'
down_revision = 'a789ec0b26df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('stat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_pointers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('three_pointers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('free_throws', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('converted_assists', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('missed_assists', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('off_rebounds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('def_rebounds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('personal_fouls', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('unsportsmanlike_fouls', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('three_sec_violations', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('five_sec_violations', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bad_passes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('traveling', sa.Integer(), nullable=True))
        batch_op.drop_column('fouls')
        batch_op.drop_column('rebounds')
        batch_op.drop_column('points')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('rebounds', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('fouls', sa.INTEGER(), nullable=True))
        batch_op.drop_column('traveling')
        batch_op.drop_column('bad_passes')
        batch_op.drop_column('five_sec_violations')
        batch_op.drop_column('three_sec_violations')
        batch_op.drop_column('unsportsmanlike_fouls')
        batch_op.drop_column('personal_fouls')
        batch_op.drop_column('def_rebounds')
        batch_op.drop_column('off_rebounds')
        batch_op.drop_column('missed_assists')
        batch_op.drop_column('converted_assists')
        batch_op.drop_column('free_throws')
        batch_op.drop_column('three_pointers')
        batch_op.drop_column('two_pointers')

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
